from pydantic import BaseModel, Field
from typing import Optional, Literal
from datetime import datetime

from bq_agentic_reasoner.models.rewrite import RewriteSet


class LLMRecommendation(BaseModel):
    """
    High-level recommendation generated by LLM.
    """

    title: str = Field(..., max_length=120)
    rationale: str = Field(..., max_length=1000)

    confidence: Literal["LOW", "MEDIUM", "HIGH"]

    category: Literal[
        "COST_OPTIMIZATION",
        "PERFORMANCE",
        "SECURITY",
        "DATA_QUALITY",
        "MODEL_RISK",
        "OTHER",
    ]


class RealtimeResult(BaseModel):
    """
    Deterministic, immediate analysis result.
    No LLM involved.
    """

    job_id: str
    timestamp: datetime

    job_type: Literal["QUERY", "BQML"]
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]

    intent: str
    estimated_cost_gb: float = Field(ge=0)
    risk: Literal["LOW", "MEDIUM", "HIGH"]

    session_id: Optional[str] = None
    status: Literal["REALTIME"] = "REALTIME"


class RunResult(RealtimeResult):
    """
    Final enriched result.
    """

    recommendation: Optional[LLMRecommendation] = None
    rewrite_set: Optional[RewriteSet] = None

    anomaly_detected: bool = False
    correlation_insight: Optional[str] = None

    status: Literal["REALTIME", "ENRICHED"] = "ENRICHED"
